### ISSUE TITLE
Long text not wrapping with RFC 2445 filter

### ISSUE THREAD

**Issue by jayhlee** [nystudio107/craft-icalendar#1]
`{% filter rfc2445 %}` isn't wrapping long text for me. It does strip HTML tags, so something's working. Is there a config I need to tinker with? I'm running the most recent version of the plugin and Craft 3.1.28. Thanks!

**Comment by khalwat** [comment]
Here's the code that does it:

https://github.com/nystudio107/craft-icalendar/blob/v1/src/services/Convert.php#L67

I haven't run into this. Did you manage to get it sorted?

**Comment by eclectiv** [comment]
Sorry for the tardy reply (two years!). Yes, was able to figure it out!

[Line 95](https://github.com/nystudio107/craft-icalendar/blob/97c024e904c29ae167005aae709fa7a4a903ce9b/src/services/Convert.php#L95) should be `return join($lines, "\n\t");`

Although the filter now wraps text to no more than 75 octets in length, there seems to be other hiccups I'm encountering. For example, wrapping the `{% filter rfc2445 %}` tags [like the provided example](https://nystudio107.com/docs/icalendar/#formatting-rfc-2445-text-in-twig) doesn't deal with html entities and line end breaks in the way that Apple's Calendar app likes. 

Strangely, when you validate the outputted ICS file, it passes the (validation)[https://icalendar.org/validator.html]. But Apple's Calendar app doesn't display the html entities, and line breaks in the `description` property, after being filtered, basically break other  properties like the `URL` property from displaying.

In the end, I ended up having to roll my own Twig-based solution and abandon using the `{% filter rfc2445 %}`. So I got everything to work, but with the trade off of having long text. Nevertheless, thanks for creating the plugin! Learned much from it to get me in the right direction!

**Comment by jayhlee** [comment]
Sorry for the tardy reply (two years!). Yes, was able to figure it out!

[Line 95](https://github.com/nystudio107/craft-icalendar/blob/97c024e904c29ae167005aae709fa7a4a903ce9b/src/services/Convert.php#L95) should be `return join($lines, "\n\t");`

Although the filter now wraps text to no more than 75 octets in length, there seems to be other hiccups I'm encountering. For example, wrapping the `{% filter rfc2445 %}` tags [like the provided example](https://nystudio107.com/docs/icalendar/#formatting-rfc-2445-text-in-twig) doesn't deal with html entities and line end breaks in the way that Apple's Calendar app likes. 

Strangely, when you validate the outputted ICS file, it passes the (validation)[https://icalendar.org/validator.html]. But Apple's Calendar app doesn't display the html entities, and line breaks in the `description` property, after being filtered, basically break other  properties like the `URL` property from displaying.

In the end, I ended up having to roll my own Twig-based solution and abandon using the `{% filter rfc2445 %}`. So I got everything to work, but with the trade off of having long text. Nevertheless, thanks for creating the plugin! Learned much from it to get me in the right direction!

**Comment by khalwat** [comment]
Could you perhaps do a PR so we can incorporate some of your changes into the plugin?

**Comment by jayhlee** [comment]
I'm not sure how to incorporate what I did, but here's the plain Twig code for my ICS file:

For the `description` value, it's intended to accept either a plain text field or a rich text field. Two drawbacks to this solution I couldn't resolve:

1. Wrapping long text
2. Line breaks are just replaced by a space. Couldn't figure out how to get the line breaks to work nicely, especially when the inputted text could be from a plain text field with simple `<br>` or rich text content (where `<p>` are stripped out and the proper line break would appropriately separate each stripped out `<p>`). 


```
{# * Set Variables ----------------------- #}
{% set entrySlug = craft.app.request.segments|last %}
{% set entry = craft.entries.slug(entrySlug).one() %}

{# * Replace Pattern Object #}
{% set replaceObj = {"\n": " ", "\r": " ", "\t": " ", "&amp;amp;" : "&", "&amp;" : "&", "&amp;quot;": "'", "&quot;": "'", "&#039;": "'"} %}

{# * Summary #}
{% set eventSummaryVar %}
{% autoescape false %}
{{ entry.title|replace(replaceObj) }}
{% endautoescape %}
{% endset %}

{# * Description #}
{% set eventDescriptionVar %}
{% autoescape false %}
{{ entry.description|striptags|replace(replaceObj)|raw }}
{% endautoescape %}
{% endset %}

{# * Output #}
{% apply spaceless %}
{% header "Content-Type: text/calendar; charset=utf-8" %}
{% header "Content-Disposition: attachment; filename=#{entry.title|truncateOnWord(60, '')|lower|kebab}.ics" %}
BEGIN:VCALENDAR
PRODID:-//{{ siteName|raw|escape }}//EN
VERSION:2.0
CALSCALE:GREGORIAN
BEGIN:VEVENT
TRANSP:TRANSPARENT
UID:{{ entry.id }}@{{ siteUrl|replace({'https://' : '', '/' : ''}) }}
DTSTAMP:{{ entry.startDate.getTimestamp() | date("Ymd", "UTC") }}T{{ entry.startTime.getTimestamp() | date("Gi", "UTC") }}00Z
DTSTART:{{ entry.startDate.getTimestamp() | date("Ymd", "UTC") }}T{{ entry.startTime.getTimestamp() | date("Gi", "UTC") }}00Z
DTEND:{{ entry.endDate.getTimestamp() | date("Ymd", "UTC") }}T{{ entry.endTime.getTimestamp() | date("Gi", "UTC") }}00Z
LOCATION:{{ entry.location }}
SUMMARY:{{ eventSummaryVar }}
DESCRIPTION:{{ eventDescriptionVar }}
URL:{{ entry.url }}
END:VEVENT
END:VCALENDAR
{% endapply %}
```

**Comment by khalwat** [comment]
Sounds to me like we only need to do two things (unless I'm missing something).

1. Change line 75 to be `return join($lines, "\n\t");`
2. do an HTML entity decode on the text

...?

**Comment by jayhlee** [comment]
I think? The line breaks with `<br>` and `<p>` together with the line wrapping made things wonky at times, so I'm not sure if that would resolve things. But it sounds like the right next steps?

**Comment by khalwat** [comment]
Welp, I'll make the changes, and you can give it a whirl... also if you could attach a file with sample data I can test against, that'd be helpful!

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-icalendar/commit/d5030923dea0b01aa0a9695a1f1e9dea1d4f9141

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-icalendar": "dev-develop as 1.1.1”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
^ pretty sure this will work as you're expecting now

**Comment by RyanRoberts** [comment]
I've just run into this problem and can confirm your dev update above does resolve it 👍

**Comment by RyanRoberts** [comment]
Spoke too soon, I'm getting an `Lines not delimited by CRLF sequence near line # 1 Reference: RFC 5545 3.1. Content Lines` error on validating.

In [d503092](https://github.com/nystudio107/craft-icalendar/commit/d5030923dea0b01aa0a9695a1f1e9dea1d4f9141) should `"\n\t"` be `"\r\n"`? Changing that validates the file for me.

**Comment by khalwat** [comment]
@RyanRoberts pushed that change in: https://github.com/nystudio107/craft-icalendar/commit/0f164583e3d08a3eb8e085f132de2d0589a1796f

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-icalendar": "dev-develop as 1.1.1”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
Lmk if it is working for you @RyanRoberts @jayhlee

**Comment by khalwat** [comment]
Released as iCalendar 1.1.1: https://github.com/nystudio107/craft-icalendar/releases/tag/1.1.1

**Comment by jayhlee** [comment]
It seems like any paragraph after the first paragraph gets cut and doesn't display—at least when it's imported in iCal (default Mac Calendar app). Here's how the outputted ICS file looks.

![para](https://user-images.githubusercontent.com/25807445/132579351-8be020b5-e0d7-4d52-86f6-44db67d01d8d.png)

**Comment by khalwat** [comment]
@jayhlee Rather than putting everything in this one issue, I'm moving this to a separate issue: https://github.com/nystudio107/craft-icalendar/issues/26

**Comment by khalwat** [comment]
@jayhlee lmk if this fixes it for you: https://github.com/nystudio107/craft-icalendar/issues/26
