### ISSUE TITLE
Event Categories

### ISSUE THREAD

**Issue by JulieVelghe** [nystudio107/craft-icalendar#31]
### Is your feature request related to a problem? Please describe.
Events from office 365 can have categories. It is not possible at the moment to get them.

### Describe the solution you would like
A clear and concise description of what you would like to have happen.
An event property that contains the categories of the event.

### Describe alternatives you have considered
A clear and concise description of any alternative solutions or features you have considered.

**Comment by khalwat** [comment]
Provide me with a sample file?

**Comment by khalwat** [comment]
@JulieVelghe ?

**Comment by JulieVelghe** [comment]
@khalwat I'm sorry for the late reply, but I think that this isn't solvable. I've found that neither google nor outlook seem to add the eventcategory to the ics-file. So the data isn't there for this plugin to possibly extract.
