### ISSUE TITLE
Outlook ICS failed to open stream: HTTP request failed

### ISSUE THREAD

**Issue by chrisrowe** [nystudio107/craft-icalendar#32]
Hitting this issue from the ics-parser dependency https://github.com/u01jmg3/ics-parser/issues/311.

I've forked and referenced commit hashes in my composer since I need this urgently but I'm opening this issue here as a polite request to update to the latest version when it's released please.

**Comment by khalwat** [comment]
Based on the semVer, you should automatically get that update when it is released: https://github.com/nystudio107/craft-icalendar/blob/develop/composer.json#L26

**Comment by chrisrowe** [comment]
3.1.2 does not satisfy constraint ^2.1.0

**Comment by khalwat** [comment]
I was going off of it being added to the 2.x.x milestone:

[u01jmg3](https://github.com/u01jmg3) added this to the [v2.x.x](https://github.com/u01jmg3/ics-parser/milestone/1) milestone [12 days ago](https://github.com/u01jmg3/ics-parser/issues/311#event-6828299947)

If that's incorrect or does not happen, I'm happy to re-open this issue.

**Comment by chrisrowe** [comment]
https://github.com/u01jmg3/ics-parser/releases v2x hasn't had any releases since 02 Nov 2020 despite many issues in that milestone being closed since then. The milestone is also "Past due by almost 5 years" so I wouldn't assume much.

**Comment by khalwat** [comment]
Gotcha. Have you tried manually changing the semVer to `^3.0.0` to see if the rest of the plugin works with the new version of `ics-parser` or if additional refactoring is needed?

I scanned the README but didn't see any kind of an upgrade guide from 2 to 3, in terms of breaking changes.

Hah, that's funny, I was looking over the commit history, and it looks like I did a PR to this repo... I don't even remember doing it: https://github.com/u01jmg3/ics-parser/issues/273

**Comment by chrisrowe** [comment]
I haven't checked thoroughly but it works for my needs, I know there are many edge cases and quirks to ics files.

**Comment by khalwat** [comment]
And away we go:

Craft 3: https://github.com/nystudio107/craft-icalendar/releases/tag/1.1.3

Craft 4: https://github.com/nystudio107/craft-icalendar/releases/tag/4.0.0

**Comment by chrisrowe** [comment]
Thanks Andrew!
