### ISSUE TITLE
Outlook ICS "Failed to open stream: HTTP request failed! HTTP/1.1 400"

### ISSUE THREAD

**Issue by SamLNL** [nystudio107/craft-icalendar#33]
### Description
I get "Failed to open stream: HTTP request failed! HTTP/1.1 400" whenever I try to use the `parseIcs` function with my Outlook ics link. The Outlook ics link is public accessible.
I've seen #32 , but I'm using the newest version and still have the problem. I also tried adding `httpUserAgent` in the config like stating [here](https://github.com/u01jmg3/ics-parser/issues/311), but without succes.

```
{% set cal = parseIcs(icsLink, {
        "httpUserAgent" : "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)"
    }) %}
```

### Versions
- Plugin version: 1.1.3
- Craft version: 3.7.46

**Comment by khalwat** [comment]
See this issue: https://github.com/nystudio107/craft-icalendar/issues/32

They need to fix it in the core library that iCalendar uses

**Comment by SamLNL** [comment]
Thanks for replying.

I've read issue #32 , but I can't seem to find a active issue regarding this issue.
Is there a active issue regarding 'They need to fix it in the core library that iCalendar uses'?

**Comment by khalwat** [comment]
Right here: https://github.com/u01jmg3/ics-parser/issues/311

I think it's been merged, but no release has been tagged yet.

**Comment by SamLNL** [comment]
Thanks!

**Comment by SamLNL** [comment]
@khalwat 
FYI

https://github.com/u01jmg3/ics-parser/issues/311 
3.2.0 is out now. This means you can now set a custom "httpUserAgent".
Got it working using this code;

```
parseIcs(calendar.icsLink, {
        "httpUserAgent" : "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)"
    }
```
